### ISSUE TITLE
Error when importing a huge table

### ISSUE THREAD

**Issue by dirkaholic** [Calder/Methink#9]
```
Writing to Rethink table 'Translation' (144901 rows)

RangeError: Maximum call stack size exceeded
    at /Users/test/dev/Methink/node_modules/rethinkdb/ast.js:3895:43
    at Function.<anonymous> (/Users/test/dev/Methink/node_modules/rethinkdb/ast.js:3897:7)
    at Function.expr (/Users/test/dev/Methink/node_modules/rethinkdb/util.js:39:16)
    at Table.<anonymous> (/Users/test/dev/Methink/node_modules/rethinkdb/ast.js:1053:45)
    at Table.insert (/Users/test/dev/Methink/node_modules/rethinkdb/util.js:60:16)
    at insertToRethink (/Users/test/dev/Methink/bin/mysql2rethink:161:36)
    at Query.<anonymous> (/Users/test/dev/Methink/bin/mysql2rethink:134:6)
    at Query._callback (/Users/test/dev/Methink/node_modules/mysql/lib/Pool.js:136:10)
    at Query.Sequence.end (/Users/test/dev/Methink/node_modules/mysql/lib/protocol/sequences/Sequence.js:78:24)
    at Query._handleFinalResultPacket (/Users/test/dev/Methink/node_modules/mysql/lib/protocol/sequences/Query.js:143:8)
    at Query.EofPacket (/Users/test/dev/Methink/node_modules/mysql/lib/protocol/sequences/Query.js:127:8)
    at Protocol._parsePacket (/Users/test/dev/Methink/node_modules/mysql/lib/protocol/Protocol.js:197:24)
    at Parser.write (/Users/test/dev/Methink/node_modules/mysql/lib/protocol/Parser.js:62:12)
    at Protocol.write (/Users/test/dev/Methink/node_modules/mysql/lib/protocol/Protocol.js:37:16)
    at Socket.ondata (stream.js:51:26)
    at Socket.emit (events.js:117:20)
```

**Comment by Calder** [comment]
Submit a PL and I'll be happy to merge it! Sorry I don't have much time these days!

**Comment by dirkaholic** [comment]
Seems to be your standard answer to issues ;-). PR is here #10

**Comment by Calder** [comment]
Haha, yeah, sorry! Graduating college and getting a job will do that to you. ;-)
